export const FORM_SUBMIT_REQUEST = 'FORM_SUBMIT_REQUEST'
export const FORM_SUBMIT_SUCCESS = 'FORM_SUBMIT_SUCCESS'
export const FORM_SUBMIT_ERROR = 'FORM_SUBMIT_ERROR'
export const FORM_RESET = 'FORM_RESET'
